### PR TITLE
License and pydocs

### PR DESCRIPTION
**Pull request by claytonk2**

### CODE REVIEW

**Review by alemon-aquaveo — CHANGES_REQUESTED** [review]
rebase with master and try again

**Comment by claytonk2** [comment]
This has been rebased with master.

**Comment by Tsubashi** [comment]
Commit messages that do not describe the changes (such as ‘a’) are unacceptable. Please amend the commit message to complete the sentence “If merged, this commit will...”

**Comment by claytonk2** [comment]
I changed the commit names.

**Review by alemon-aquaveo — APPROVED** [review]

**Pull request merged**
